# Generated by Django 4.2.1 on 2023-05-27 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teller', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.language')),
                ('teller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.teller')),
            ],
        ),
    ]
