# Generated by Django 4.2.1 on 2023-06-12 08:06

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_problist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problist',
            name='username',
            field=models.CharField(max_length=30, verbose_name=common.models.Userdata),
        ),
    ]
